
print ()
print ("Downloading Lectures...")
file_name = wget.download(lecture_link)
print ("Lectures have been downloaded")
print()
print ("Downloading Homeworks...")
file_name = wget.download(homework_link)
print ("Homeworks have been downloaded")
print()
print ("Downloading Tutorials...")
file_name = wget.download(tutorial_link)
print ("Tutorials have been downloaded")
print()
print ("Downloading Labs...")
file_name = wget.download(lab_link)
print ("Labs have been downloaded")
print()
print ("Downloading Solutions...")
file_name = wget.download(solution_link)
print ("Solutions have been downloaded")
print()
print ("Downloading Exams...")
file_name = wget.download(exam_link)
print ("Exams have been downloaded")
print()
print ("Downloading Projects...")
file_name = wget.download(project_link)
print ("Projects have been downloaded")
print()
print ("Downloading Others...")
file_name = wget.download(other_link)
print ()